import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/providers/StoreProvider";
import Header from "@/components/Header";
import { Toaster } from "sonner";
import SetProductsToState from "@/components/SetProductsToState";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-7xl mx-auto bg-white lg:px-20 px-2`}
        >
          <Header />
          {children}
          <Toaster />
          <SetProductsToState />
        </body>
      </StoreProvider>
    </html>
  );
}
